// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolExpFileLoc
{
    static class Vsix
    {
        public const string Id = "c6775dc3-3a53-4721-a32e-81cc53f76e3f";
        public const string Name = "Solution Explorer File Location";
        public const string Description = @"The easiest way of knowing the location of a file within the filters in solution explorer. Handy for a massive list of files in the solution.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vivian Lobo";
        public const string Tags = "solution explorer, files, location";
    }
}
