// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolExpFileLoc
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFileLocCommandPackageString = "79a66ad0-7cba-4f73-bcd6-135c48322951";
        public const string guidFileLocCommandPackageCmdSetString = "f1a36b80-a278-40b8-bbb3-25257ddce6f4";
        public const string guidImagesString = "8c8fc72b-6d80-42d3-9258-e94ff8682919";
        public static Guid guidFileLocCommandPackage = new Guid(guidFileLocCommandPackageString);
        public static Guid guidFileLocCommandPackageCmdSet = new Guid(guidFileLocCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FileLocCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
